# use the default golang container from Docker Hub
box: golang

# The steps that will be executed in the build pipeline
build:
  steps:
    # golint step!
    - wercker/golint

    # Build the project
    - script:
        name: go build
        code: |
          go build -v $(go list ./... | grep -v vendor)

    # Test the project
    - script:
        name: go test
        code: |
          go test -v $(go list ./... | grep -v vendor)
